name: Databricks Bundle CI/CD

on:
  push:
    branches:
      - main

  workflow_dispatch:

jobs:
  deploy-prod:
    name: Deploy PROD
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Databricks CLI
        uses: databricks/setup-cli@v0.221.0

      - name: Debug bundle root
        run: |
          pwd
          ls -la
          find . -name databricks.yml

      - name: Deploy Databricks Bundle (PROD)
        working-directory: bundle
        run: databricks bundle deploy --target prod
        env:
          DATABRICKS_HOST: ${{ secrets.DATABRICKS_HOST_PROD }}
          DATABRICKS_TOKEN: ${{ secrets.DATABRICKS_TOKEN_PROD }}


